import {Bold, Italic, PackageSearch, Plus, RotateCcw, Sparkles, Trash2, Underline, X} from 'lucide-react';
import {useEffect, useMemo, useState} from 'react';

import {getCartUpsell, saveCartUpsell, type CartUpsellConfiguration, type RichTextStyle, type ShopifyResource, type UpsellRecommendation, type UpsellRule} from './api';

const richText = (text: string): RichTextStyle => ({text, bold: true, italic: false, underline: false, font_size: 16});
const itemId = () => (crypto.randomUUID?.() ?? `${Date.now()}${Math.random()}`).replaceAll('-', '').replace('.', '').slice(0, 16);
const copy = (value: CartUpsellConfiguration) => structuredClone(value);
export const defaultUpsell: CartUpsellConfiguration = {upsell_enabled: false, upsell_cap_quantity: true, upsell_max_quantity: 1, upsell_variant_behavior: 'variant_popup', upsell_ai_enabled: true, upsell_ai_title: richText('Recommended for you'), upsell_ai_background_color: '#FFFFFF', upsell_ai_text_color: '#202124', upsell_ai_preference: 'complementary', upsell_ai_product_count: 6, upsell_rule_fallback_enabled: false, upsell_rules: []};
const newRule = (): UpsellRule => ({id: itemId(), title: richText('You may also like'), product_count: 4, background_color: '#FFFFFF', text_color: '#202124', applicable_on: 'all', trigger_ids: [], trigger_titles: [], trigger_product_ids: [], recommendations: []});

function Toggle({checked, label, description, onChange}: {checked: boolean; label: string; description: string; onChange: (value: boolean) => void}) {
  return <label className="setting-toggle"><span className="setting-toggle__copy"><strong>{label}</strong><small>{description}</small></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span className="toggle-track" aria-hidden="true"><span /></span></label>;
}
function NumberField({label, value, max = 99, onChange}: {label: string; value: number; max?: number; onChange: (value: number) => void}) {
  return <label className="field"><span>{label}</span><input type="number" min={1} max={max} value={value} onChange={(event) => onChange(Math.min(max, Math.max(1, Number(event.target.value))))} /></label>;
}
function ColorField({label, value, onChange}: {label: string; value: string; onChange: (value: string) => void}) {
  return <label className="field color-field"><span>{label}</span><span className="color-input-wrap"><input className="color-swatch" type="color" value={value} onChange={(event) => onChange(event.target.value.toUpperCase())} /><input value={value} maxLength={7} onChange={(event) => onChange(event.target.value.toUpperCase())} /></span></label>;
}
function RichField({label, value, onChange}: {label: string; value: RichTextStyle; onChange: (value: RichTextStyle) => void}) {
  const set = <K extends keyof RichTextStyle>(key: K, next: RichTextStyle[K]) => onChange({...value, [key]: next});
  return <div className="field rich-field"><span>{label}</span><div className="rich-toolbar"><button className={value.bold ? 'is-active' : ''} type="button" onClick={() => set('bold', !value.bold)} aria-label="Bold"><Bold size={15} /></button><button className={value.italic ? 'is-active' : ''} type="button" onClick={() => set('italic', !value.italic)} aria-label="Italic"><Italic size={15} /></button><button className={value.underline ? 'is-active' : ''} type="button" onClick={() => set('underline', !value.underline)} aria-label="Underline"><Underline size={15} /></button><select value={value.font_size} onChange={(event) => set('font_size', Number(event.target.value) as RichTextStyle['font_size'])}>{[12, 14, 16, 18, 20].map((size) => <option value={size} key={size}>{size}px</option>)}</select></div><input value={value.text} maxLength={64} onChange={(event) => set('text', event.target.value)} /><small>{value.text.length} / 64</small></div>;
}
function ChoiceGroup({name, value, options, onChange}: {name: string; value: string; options: {value: string; label: string; description: string}[]; onChange: (value: string) => void}) {
  return <div className="choice-list choice-list--two" role="radiogroup" aria-label={name}>{options.map((option) => <label key={option.value}><input type="radio" name={name} checked={value === option.value} onChange={() => onChange(option.value)} /><span><strong>{option.label}</strong><small>{option.description}</small></span></label>)}</div>;
}
function Section({title, description, children}: {title: string; description: string; children: React.ReactNode}) {
  return <section className="appearance-section"><header><h2>{title}</h2><p>{description}</p></header><div className="appearance-section__body">{children}</div></section>;
}
async function pickMany(type: 'variant' | 'product' | 'collection') {
  return window.shopify?.resourcePicker ? (await window.shopify.resourcePicker({type, action: 'select', multiple: 20}) ?? []) : [];
}
function asRecommendation(resource: ShopifyResource): UpsellRecommendation | null {
  const product = resource.product ?? resource;
  const variant = resource.product ? resource : resource.variants?.[0];
  if (!variant || !variant.id.includes('/ProductVariant/') || !product.id.includes('/Product/')) return null;
  return {variant_id: variant.id, variant_title: variant.displayName ?? variant.title ?? 'Default variant', product_id: product.id, product_title: product.title ?? product.displayName ?? 'Product', product_handle: product.handle ?? '', image_url: product.image?.originalSrc ?? product.image?.url ?? product.images?.[0]?.originalSrc ?? product.images?.[0]?.url ?? '', price: variant.price ?? ''};
}

export function CartUpsellPage({previewMode}: {previewMode: boolean}) {
  const [configuration, setConfiguration] = useState(copy(defaultUpsell));
  const [saved, setSaved] = useState(copy(defaultUpsell));
  const [loading, setLoading] = useState(!previewMode);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const dirty = useMemo(() => JSON.stringify(configuration) !== JSON.stringify(saved), [configuration, saved]);
  const update = <K extends keyof CartUpsellConfiguration>(key: K, value: CartUpsellConfiguration[K]) => setConfiguration((current) => ({...current, [key]: value}));
  const updateRule = (id: string, change: Partial<UpsellRule>) => update('upsell_rules', configuration.upsell_rules.map((rule) => rule.id === id ? {...rule, ...change} : rule));

  useEffect(() => {
    if (previewMode) return;
    getCartUpsell().then(({updated_at: _, ...next}) => {setConfiguration(copy(next)); setSaved(copy(next));}).catch((error: unknown) => setMessage(error instanceof Error ? error.message : 'Could not load upsells.')).finally(() => setLoading(false));
  }, [previewMode]);
  const save = async () => {
    setSaving(true); setMessage('');
    try { const {updated_at: _, ...next} = await saveCartUpsell(configuration); setConfiguration(copy(next)); setSaved(copy(next)); setMessage('Cart upsells published.'); }
    catch (error) { setMessage(error instanceof Error ? error.message : 'Could not save upsells.'); }
    finally { setSaving(false); }
  };
  if (loading) return <section className="state-panel"><div className="spinner" /><p>Loading cart upsells.</p></section>;

  return <div className="appearance-page"><header className="appearance-header"><div><p className="eyebrow">Cart experience</p><h1>Cart upsell</h1><p>Recommend relevant products and recalculate suggestions as the cart changes.</p></div><div className="appearance-header__actions"><button className="button button--secondary" type="button" disabled={!dirty} onClick={() => setConfiguration(copy(saved))}><RotateCcw size={16} />Discard</button><button className="button button--primary" type="button" disabled={!dirty || saving || previewMode} onClick={save}>{saving ? 'Saving...' : 'Save'}</button></div></header>{message && <p className="appearance-message" role="status">{message}</p>}
    <div className="appearance-workspace"><div className="appearance-editor">
      <Section title="Upsell settings" description="Control shared recommendation behaviour."><Toggle checked={configuration.upsell_enabled} label="Enable cart upsells" description="Show recommendations when the cart contains products." onChange={(value) => update('upsell_enabled', value)} /><div className="nested-settings"><Toggle checked={configuration.upsell_cap_quantity} label="Cap quantity per upsell SKU" description="Limit quantities added from recommendation cards." onChange={(value) => update('upsell_cap_quantity', value)} />{configuration.upsell_cap_quantity && <NumberField label="Maximum quantity" value={configuration.upsell_max_quantity} onChange={(value) => update('upsell_max_quantity', value)} />}</div><ChoiceGroup name="variant-behaviour" value={configuration.upsell_variant_behavior} onChange={(value) => update('upsell_variant_behavior', value as CartUpsellConfiguration['upsell_variant_behavior'])} options={[{value: 'variant_popup', label: 'Variant selection', description: 'Choose an available variant before adding.'}, {value: 'product_popup', label: 'Product details', description: 'Open product information and add controls.'}]} /></Section>
      <Section title="AI recommendations" description="Use Shopify recommendations with an optional rules fallback."><Toggle checked={configuration.upsell_ai_enabled} label="Enable AI recommendations" description="Recommend products based on current cart lines." onChange={(value) => update('upsell_ai_enabled', value)} /><RichField label="Section title" value={configuration.upsell_ai_title} onChange={(value) => update('upsell_ai_title', value)} /><div className="field-grid"><ColorField label="Background color" value={configuration.upsell_ai_background_color} onChange={(value) => update('upsell_ai_background_color', value)} /><ColorField label="Text color" value={configuration.upsell_ai_text_color} onChange={(value) => update('upsell_ai_text_color', value)} /></div><ChoiceGroup name="ai-preference" value={configuration.upsell_ai_preference} onChange={(value) => update('upsell_ai_preference', value as CartUpsellConfiguration['upsell_ai_preference'])} options={[{value: 'complementary', label: 'Complementary', description: 'Products commonly bought together.'}, {value: 'related', label: 'Related', description: 'Similar products shoppers may consider.'}]} /><NumberField label="Maximum products" max={10} value={configuration.upsell_ai_product_count} onChange={(value) => update('upsell_ai_product_count', value)} /><Toggle checked={configuration.upsell_rule_fallback_enabled} label="Use rules as fallback" description="Use matching rules only when AI returns no products." onChange={(value) => update('upsell_rule_fallback_enabled', value)} /></Section>
      <Section title="Rule-based recommendations" description="Choose exact recommendations for all carts or selected products and collections."><div className="feature-list">{configuration.upsell_rules.map((rule, index) => <article className="feature-item" key={rule.id}><div className="feature-item__header"><strong>Rule {index + 1}</strong><button className="icon-button icon-button--danger" type="button" onClick={() => update('upsell_rules', configuration.upsell_rules.filter((item) => item.id !== rule.id))} aria-label={`Remove rule ${index + 1}`}><Trash2 size={16} /></button></div><RichField label="Title" value={rule.title} onChange={(value) => updateRule(rule.id, {title: value})} /><div className="field-grid"><NumberField label="Products to display" max={10} value={rule.product_count} onChange={(value) => updateRule(rule.id, {product_count: value})} /><ColorField label="Background color" value={rule.background_color} onChange={(value) => updateRule(rule.id, {background_color: value})} /><ColorField label="Text color" value={rule.text_color} onChange={(value) => updateRule(rule.id, {text_color: value})} /></div><ChoiceGroup name={`scope-${rule.id}`} value={rule.applicable_on} onChange={(value) => updateRule(rule.id, {applicable_on: value as UpsellRule['applicable_on'], trigger_ids: [], trigger_titles: [], trigger_product_ids: []})} options={[{value: 'all', label: 'All products', description: 'Apply to every non-empty cart.'}, {value: 'products', label: 'Specific products', description: 'Match selected cart products.'}, {value: 'collections', label: 'Specific collections', description: 'Match products in selected collections.'}]} />
          {rule.applicable_on !== 'all' && <ResourceList label={`Applicable ${rule.applicable_on}`} items={rule.trigger_titles} disabled={previewMode} onPick={async () => {const resources = await pickMany(rule.applicable_on === 'products' ? 'product' : 'collection'); updateRule(rule.id, {trigger_ids: resources.map((item) => item.id), trigger_titles: resources.map((item) => item.title ?? item.displayName ?? 'Selected item'), trigger_product_ids: resources.flatMap((item) => item.products?.map((product) => product.id) ?? [])});}} onRemove={(position) => updateRule(rule.id, {trigger_ids: rule.trigger_ids.filter((_, index) => index !== position), trigger_titles: rule.trigger_titles.filter((_, index) => index !== position)})} />}
          <ResourceList label="Recommended variants" items={rule.recommendations.map((item) => `${item.product_title} - ${item.variant_title}`)} disabled={previewMode} onPick={async () => {const selected = (await pickMany('variant')).map(asRecommendation).filter((item): item is UpsellRecommendation => Boolean(item)); updateRule(rule.id, {recommendations: Array.from(new Map([...rule.recommendations, ...selected].map((item) => [item.variant_id, item])).values())});}} onRemove={(position) => updateRule(rule.id, {recommendations: rule.recommendations.filter((_, index) => index !== position)})} /></article>)}</div><button className="button button--secondary" type="button" onClick={() => update('upsell_rules', [...configuration.upsell_rules, newRule()])}><Plus size={16} />Add rule</button></Section>
    </div><aside className="cart-preview" aria-label="Cart preview"><div className="cart-preview__label"><Sparkles size={15} />Live preview</div><div className="upsell-preview" style={{background: configuration.upsell_ai_background_color, color: configuration.upsell_ai_text_color}}><strong style={{fontSize: configuration.upsell_ai_title.font_size}}>{configuration.upsell_ai_title.text}</strong><div>{['Everyday tote', 'Travel bottle'].map((title) => <article key={title}><span className="upsell-preview__image" /><b>{title}</b><small>Rs. 799</small><button type="button" disabled>+ Add</button></article>)}</div></div><p className="preview-note">Preview controls are intentionally disabled.</p></aside></div></div>;
}

function ResourceList({label, items, disabled, onPick, onRemove}: {label: string; items: string[]; disabled: boolean; onPick: () => void; onRemove: (position: number) => void}) {
  return <div className="field"><span>{label}</span><button className="button button--secondary resource-picker-button" type="button" disabled={disabled || !window.shopify?.resourcePicker} onClick={onPick}><PackageSearch size={16} />Select</button><div className="resource-chips">{items.map((item, index) => <span key={`${item}-${index}`}>{item}<button type="button" onClick={() => onRemove(index)} aria-label={`Remove ${item}`}><X size={13} /></button></span>)}</div></div>;
}
