query Input {
  cart {
    lines {
      id
      quantity
      giftOffer: attribute(key: "_pragma_site_cart_free_gift_offer") {
        value
      }
      cost {
        subtotalAmount {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
          }
        }
      }
    }
  }
  discount {
    discountClasses
    configuration: metafield(namespace: "$app", key: "function-configuration") {
      jsonValue
    }
  }
}
